// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdZYC3NkWlvY7HNAR6_4MD7x7igfrDD88',
    appId: '1:309213853245:web:c16e27c57ea6ea75671c54',
    messagingSenderId: '309213853245',
    projectId: 'chat-app-f83fd',
    authDomain: 'chat-app-f83fd.firebaseapp.com',
    databaseURL: 'https://chat-app-f83fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-f83fd.appspot.com',
    measurementId: 'G-TPVTQ3BYZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IqynC8QI1d7xoYQ-3ZXfhmcLVyPiTAU',
    appId: '1:309213853245:android:483d3b608d2c95e4671c54',
    messagingSenderId: '309213853245',
    projectId: 'chat-app-f83fd',
    databaseURL: 'https://chat-app-f83fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-f83fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaK0ZKp5HLB6E5Bn_T6PyuGMirXnsWsk',
    appId: '1:309213853245:ios:cd5f1f27565e20be671c54',
    messagingSenderId: '309213853245',
    projectId: 'chat-app-f83fd',
    databaseURL: 'https://chat-app-f83fd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-f83fd.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
